SonarSource/helm-chart-sonarqube

- charts/sonarqube/values.yaml
The version in the `values.yaml` was set to 8.8-community, while the `Chart.yaml` implies it would install 8.9-community.
* update `values.yaml` to expected appVersion from `Chart.yaml`
* n/a
> fix missaligned appVersion

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
This property was already present in the `Deployment` kind but was absent in the `StatefulSet` kind.
* add `serviceAccountName` logic from `Deployment` kind template to `StatefulSet` kind
* closes #12
> add missing serviceAccountName property

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/install-plugins.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
- charts/sonarqube/values.yaml
Since the currently used `rjkernick/alpine-wget:latest` is unmaintained it can be seen as a security risk and might get blocked by security restrictions in certain deployments. To circumvent this this PR replicates what #10 started and moved the only use of the image to use a up to date `curl` image. This in turn required an update of the plugin install script to use `curl`.
* migrates plugin-install init container to use `curlimages/curl:7.76.1` instead of `rjkernick/alpine-wget:latest`
* updated plugin install script to use `curl` instead of `wget`
* change how proxy settings are handled for the plugin script (unifies it with the Prometheus init container) 
* fix a possible bug with the Prometheus init container if `env` would have been set in values
* closes #15 
* The `Deployment` …
> change to use curl image for plugin download

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
When deploying a change for the Prometheus exporter agents (just `prometheusExporter.config` and/or `prometheusExporter.esConfig`, and nothing else), SQ doesn't restart.  Too bad I did not see that before submitting #37...
Fixed by adding more checksum annotations.
> restart SQ when only modifying the exporter agents config

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/_helpers.tpl
- charts/sonarqube-dce/templates/secret.yaml
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube-dce/values.yaml
While working on our internal deployment i noticed two things: 
1. we can remove the `initSysctl` init container from the application pods
2. we can source the jwt secret for the application pods from an external secret
sadly this is not possible for the `monitoringPasscode`
> BUILD-1107 polishing

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
reported in the [community](https://community.sonarsource.com/t/cacerts-build-blocked-in-kubernetes-helm-chart/48543)
> fixed blocking conditional for additional ca-certificates

- charts/sonarqube-lts/CHANGELOG.md
- charts/sonarqube-lts/Chart.yaml
- charts/sonarqube-lts/templates/pvc.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/pvc.yaml
**What happens:**
When attempting to apply this Helm Chart with `persistence.enabled` set to `true` I receive this error:
```
Error: PersistentVolumeClaim "sonarqube-sonarqube" is invalid: metadata.labels: Invalid value: "sonarqube-1.1.1+98": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
This seems to be due to the label `chart` on the PVC, which is set to `{{ .Chart.Name }}-{{ .Chart.Version }}`. With the versioning currently on the chart, this adds a `+` to the label, which is not allowed in Kubernetes.
**What's expected:**
All resources deploy, including the PVC …
> Fix PVC `chart` label

- charts/sonarqube-lts/README.md
- charts/sonarqube/README.md
Didn't realize until I saw the published charts that I should have been working against a char limit for initial impact in the search results list
> Update for a better excerpt

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/tests/sonarqube-test.yaml
- charts/sonarqube/values.yaml
Currently there is no way to enable tests while deploying to a cluster with enabled ResourceQuota admission control plugin. This PR adds a few missing `resources:` keys to the templates and values.yaml.
> Add resources to tests pod templates

- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/README.md
Documentation changes do not need CI to pass and the `9.1` tag is the same hash as `9.1.0`
> [skip ci] SONAR-15402 fixup to set the right image tags

- charts/sonarqube-dce/README.md
- charts/sonarqube/README.md
I had this change for a time in a local branch, updated it and want to propose this change to make the table easier to read / find the values you are looking for.
It also gets rid of the many blank spaces in the Markdown Table which made it unnecessarily cumbersome to edit (IMHO).
An `.adoc` table would be even easier to edit from a markup perspective, yet that is even more subjective than this change already is, so I decided against proposing a markup language change.
Feedback welcome as always and I hope I didn't miss any options. 
* split up values table into smaller section tables of interest
* n/a?
> docs: proposal to split up value table into sections of interest

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/change-admin-password-hook.yml
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube-dce/templates/sonarqube-search.yaml
- charts/sonarqube-dce/templates/tests/sonarqube-test.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/change-admin-password-hook.yml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
- charts/sonarqube/templates/tests/sonarqube-test.yaml
- charts/sonarqube/values.yaml
At the moment it is only possible to set one pull secret through `image.pullSecret`. But for my use-case I would like to be able to use multiple `imagePullSecrets` to be able to pull the images from different private registries.
Some changes along the lines of this PR would be required, would a feature like this to acceptable to merge?
---
In this PR I went for the easy way and replaced `image.pullSecret` with `image.pullSecrets` with a bit of effort it's also possible to implement this in a way that retains compatibility.
> Add support for multiple image.pullSecrets

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/route.yaml
- charts/sonarqube/values.yaml
Allow overriding the host a route through a value. An empty `route.host` will keep the old behaviour of a defaulted host.
> Allow overriding the host of a route

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
This PR should address issue #139. Please let me know if I'm missing anything or if there is a better way to handle this.
Changes:
- Add missing passcode from list of environment variables ( sonarqube )
- update livenessProbe to use exec commands and prevent the passcode from being templated in plaintext in the manifest ( sonarqube, sonarqube-dce )
> Issue-139 Fixes and improvements on use of monitoring passcode

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
Not all instances of the check if caCerts were enabled were updated so it would still try to add the volumes even though it is disabled. This causes the deployment to fail.
> Updated all instances of the caCerts enabled check

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/serviceaccount.yaml
The `automountServiceAccountToken` property defaults to `true`, this PR opts out of automounting that token to reduce container vulnerabilities.
> Do not automatically mount Service Account token

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/change-admin-password-hook.yml
- charts/sonarqube-dce/templates/secret.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/change-admin-password-hook.yml
- charts/sonarqube/templates/secret.yaml
----
While the change admin password hook is very handy, we noticed it exposes the admin password in the deploy logs. For security reasons, we need this password to be stored as a k8s secret.
> Secure admin password in k8s secret

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/change-admin-password-hook.yml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/change-admin-password-hook.yml
----
We noticed in our gatekeeper constraints that the admin password hook was using the default service account even though we specified a service account to be used. This change just uses that specified service account.
> Specify service account name in change admin password hook

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/install-plugins.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/install-plugins.yaml
**Description**
There is currently an issue where if a user needs to provide credentials to a server in order to retrieve a plugin for installation, the .netrc file that is created by the chart (using the secret specified at `.Values.plugins.netrcCreds`) is not used. This causes issues in scenarios where users want to install internal plugins that have been published to private artifact registries that don't allow anonymous access.
Normally we would just need to specify the `'-n'` flag to curl to tell it to use the .netrc file in the users home directory, but as we have mounted the .netrc secret at the root directory (see [here](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L127)), we have to specify the `'--netrc-file'` flag to …
> Specify location of .netrc file if netrcCreds are provided for plugin installation.

- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-lts/Chart.yaml
- charts/sonarqube/Chart.yaml
the "skip ci" needs to be squashed away during merge, but i think bumping the chart version number is not necessary here
> [skip ci] handover

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
Without setting SONAR_WEB_CONTEXT, using a non-default path doesn't work.
This fixes https://github.com/SonarSource/helm-chart-sonarqube/issues/205
This is not a change in the chart itself, but in the example config.
> Add SONAR_WEB_CONTEXT example in comments

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-lts/CHANGELOG.md
- charts/sonarqube-lts/Chart.yaml
- charts/sonarqube-lts/README.md
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
This PR simply adds to the documentation that it's possible to provide extra annotations for the ingress resource.
`charts/sonarqube/templates/ingress.yaml` already reads the `ingress.annotations` field, it's just that the README didn't mention it.
The annotations can be important for use cases that include the AWS Application Load Balancer Controller.
Example use case:
```yaml
---
ingress:
annotations:
alb.ingress.kubernetes.io/scheme: internet-facing
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
```
> Docs: add ingress annotations in README

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/route.yaml
Hi,
Name of the Openshift/OKD should use fullname instead of name like other resources.
Thanks!
> Fix Openshift route name

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/route.yaml
- charts/sonarqube/values.yaml
Hi (again),
Labels and annotations are supported for Ingress resource but sadly not for the Openshift/OKD Route.
This PR add support for adding extra labels and annotations like the Ingress resource.
Annotations are required to configure Route behavior like timeout : https://docs.openshift.com/container-platform/4.10/networking/routes/route-configuration.html#nw-route-specific-annotations_route-configuration
Regards,
> Add support for labels and route annotations like ingress

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube-lts/CHANGELOG.md
- charts/sonarqube-lts/Chart.yaml
- charts/sonarqube-lts/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
I add a reference about generating self-signed certificates (and private keys) and registering the corresponding secret in the cluster.
> DOCKER-77 Add documentation for ingress tls in helm charts

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/sonarqube-sts.yaml
- charts/sonarqube/values.schema.json
- charts/sonarqube/values.yaml
We only support 1 replica for deployment and statefulset types in sonarqube and sonarqube-lts charts. Therefore, we set 0 and 1 as allowed values for `replicas`, having 1 as the default value.
> DOCKER-63 Set the number of allowed replicas in sonarqube and sonarqube-lts charts

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/values.yaml
Our values.yml and readme.md lack consistent documentation about the jwt secret. We revise the existing guidelines and specify more where needed.
> DOCKER 79 Add documentation in the DCE chart on how to generate the jwt secret

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/requirements.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/requirements.yaml
We have to update our `apiVersion` to `v2`, as this is the recommended API used by Helm 3 (which is the version that we support).
We checked the official [migration guidelines](https://helm.sh/docs/topics/v2_v3_migration/) and make our chart complaint  with the following changes in `apiVersion=v2`:
- "Dynamically linked chart dependencies moved to Chart.yaml (requirements.yaml removed and requirements --> dependencies)"
- "Charts have a type metadata field to define the chart to be of an application or library chart. It is application by default which means it is renderable and installable"
> DOCKER-64 bump apiVersion to v2 and refactor deprecated configs

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
Based on my current understanding, we have 4 ways to specify these properties:
- Rely on the default `sonar.properties` already available inside the containers
- Mount your own `sonar.properties`
- Mount your own `secret.properties` (from a secret spec)
- A combination of 3 and 2 
In the DCE chart, I think that we cover correctly only case 1. We could probably refactor the code in this way to achieve the other cases.
> DOCKER-78 fix wrong conditions for sonarProperties and sonarSecretProperties and documentation update

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/change-admin-password-hook.yml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/change-admin-password-hook.yml
- charts/sonarqube/values.yaml
Currently, users cannot define their own secret in the cluster for setting the current and custom passwords at the startup. This PR aims at providing our standard and dce chart users with this possibility.
> DOCKER-80 add the possibility to use an existing secret for change admin password hook

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/secret.yaml
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/secret.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
- charts/sonarqube/values.yaml
Currently, we cannot load the monitoringPasscode from an existing secret and we define it among liveness HTTP headers in clear text (DOCKER-65).
In this PR, we add the possibility to get this value from a secret and define a new liveness probe that masks the HTTP header.
> DOCKER-81 Add support for monitoringPasscode passed as a secret and removal of in-clear-text livenessprobe httpheader

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/networkpolicy.yaml
- charts/sonarqube/values.yaml
For the prometheusExporter namespace selector, use the `networkPolicy.prometheusNamespace` value instead of using a fixed value.
> feat(networkpolicies): use the prometheusNamespace value

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/values.yaml
We set the application nodes to use an incorrect image (`9.6.0-datacenter-app` instead of `9.6.1-datacenter-app`).
> DOCKER-92 fix the wrong image's tag in application nodes

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/networkpolicy.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/networkpolicy.yaml
When using NetworkPolicies with `.Values.networkPolicy.additionalNetworkPolicys` the templating result is broken because of the right-dash curly brace of the previous `if` statement that removes the next newline.
```yaml
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
name: test-sonarqube-database
labels:
app: sonarqube
chart: sonarqube-5.4.0
release: test
heritage: Helm
spec:
podSelector:
matchLabels:
app.kubernetes.io/name: postgresql
policyTypes:
- Ingress
- Egress
ingress:
- from:
- podSelector:
matchLabels:
app: sonarqube
ports:
- port: 5432
egress:
- to:
- namespaceSelector: {}
podSelector:
matchLabels:
k8s-app: kube-dns
ports:
- port: 53
protocol: UDP---
kind: NetworkPolicy
apiVersion: …
```
> Remove the right-dash curly brace to prevent chomping whitespace

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.lock
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/requirements.lock
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.lock
- charts/sonarqube/Chart.yaml
- charts/sonarqube/requirements.lock
The required version of the PostgreSQL chart is no longer available. This prevents users from installing our charts. We need to fix the repository used to fetch it (the bitnami chart got moved to another repository).
> SQHELM-2 Update the postgresql chart's repository

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/values.yaml
We do not recommend any maximum allowed payload sizes in our ingress configuration. This might end up in `Error 413` in a real scenario. Therefore, we add a new annotation in our chart with a default value set to 64m (after investigation).
> SQHELM-1 Set a new maximum allowed size of the client request body

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
We need to drop the support for EoL versions. This PR update the documentation, as direct consequence of the compatibility tests that we did before.
> SQHELM-86 Update the supported kubernetes versions

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/templates/sonarqube-search.yaml
Co-authored-by: @BitExodus
This PR is based on the contribution made by Enrique García the context of [this PR](https://github.com/SonarSource/helm-chart-sonarqube/pull/285).
> SQHELM-110 Fix the SonarQube DCE chart volume mounts (init-fs container)

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube-dce/templates/sonarqube-application.yaml
- charts/sonarqube-dce/templates/sonarqube-search.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
* allow setting priorityClassName for StatefulSets
Co-authored-by: Artem Kajalainen <artem.kajalainen@virta.global>
This PR is based on the contribution made by Artem Kajalainenin the context of this [PR](https://github.com/SonarSource/helm-chart-sonarqube/pull/279)
> SQHELM-109 allow setting priorityClassName for StatefulSets

- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/sonarqube-sts.yaml
This PR adds support for `extraVolumes` and `extraVolumeMounts`.
Useful for example when mounting secrets with a CSI provider (like vault) which is my specific use case for this.
---
> feat: added support for extraVolumes and extraVolumeMounts

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/README.md
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
The current READMEs for all charts show a multiline string example for the `cacert` secret, but specify `data` rather than `stringData`. To make things a little more clear the example should be `stringData`.
Signed-off-by: Micah Nagel <micah.nagel@defenseunicorns.com>
As docs changes, I'm not sure if these require a chart bump/changelog entry?
> SQHELM-111 Clarify doc for custom cacert secret

- .cirrus.yaml
The definition of the chart_testing task has been modified in order to run after each merge to master and during the nightly QA.
> [NO-JIRA] Update cirrus config to skip promote task and run tests on nightly cron executed QA

- .cirrus.yaml
`--all` will lint and test all charts, disabling changed charts detection and version increment checking.
Those checks are mostly causing merge conflict for user.
This change will allow us to release more easily on release-branches with the new release model.
> SONAR-18987 run test always, regardless of chart changes

- charts/sonarqube-dce/templates/sonarqube-application.yaml
Ensure the application nodes use
`Values.ApplicationNodes.containerSecurityContext` instead of the non-existing `Values.containerSecurityContext`.
> SONAR-19438 fixes nested key

- charts/sonarqube-dce/README.md
- charts/sonarqube/README.md
Updates both Charts READMEs' to include a link to our official Kubernetes Environment recommendations due to the upcoming change of Pod Security Policies to Pod Security Standards.
> SONAR-19382 links to the official documentation

- .cirrus.yaml
We adopt a new release policy where every change does not require a bump on the chart's version. This PR removes an old check and align the LTS policy with what we follow on the main development stream.
> [NO JIRA] Remove strict check on version bumps

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube-dce/values.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
Kubernetes version: v1.26.6
When not using the root user, the initSysctl throws an error: 
```sysctl: permission denied on key "vm.max_map_count", ignoring```
After this, elasticSearch refuses to start:
```bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]```
> Run the initSysctl initcontainer as root

- charts/sonarqube-dce/README.md
- charts/sonarqube/README.md
- Broken hyperlinks to the SonarQube documentation were fixed in the Helm chart READMEs. 
- In addition, the documentation URLs were updated to reflect the correct docs domain
- no updates to the CHANGELOG are made for these improvements
> Fix broken link to the docs and update with new domain URLs

- charts/sonarqube-dce/README.md
- charts/sonarqube/README.md
[SONAR-24127](https://sonarsource.atlassian.net/browse/SONAR-24127)
[SONAR-24127]: https://sonarsource.atlassian.net/browse/SONAR-24127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24127 Document 2025.1 LTA breaking changes

- .cirrus/tasks.yml
- .cirrus/tasks_sonarqube.yml
- .cirrus/tasks_sonarqube_dce.yml
- .cirrus/tasks_templates.yml
- ct-sonarqube-dce-test.yaml
- ct-sonarqube-test.yaml
[SONAR-24169](https://sonarsource.atlassian.net/browse/SONAR-24169)
Part of SONAR-23970
[SONAR-24169]: https://sonarsource.atlassian.net/browse/SONAR-24169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24169 Splits test on kind into multiple tests

- .cirrus/tasks_gcp_marketplace.yml
- google-cloud-marketplace-k8s-app/Dockerfile
- google-cloud-marketplace-k8s-app/schema.yaml
[SONAR-24200](https://sonarsource.atlassian.net/browse/SONAR-24200)
[SONAR-24200]: https://sonarsource.atlassian.net/browse/SONAR-24200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24200 Add new required annotation in the GCP images

- .cirrus/tasks_gcp_marketplace.yml
- google-cloud-marketplace-k8s-app/Dockerfile
[SONAR-24220](https://sonarsource.atlassian.net/browse/SONAR-24220)
[SONAR-24220]: https://sonarsource.atlassian.net/browse/SONAR-24220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24220 Set a new GCP-Service-name annotation

- .cirrus/tasks_gcp_marketplace.yml
[SONAR-24632](https://sonarsource.atlassian.net/browse/SONAR-24632)
Part of SONAR-24631
[SONAR-24632]: https://sonarsource.atlassian.net/browse/SONAR-24632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24632 Fixes GCP release tasks

- charts/sonarqube-dce/CHANGELOG.md
- charts/sonarqube-dce/Chart.lock
- charts/sonarqube-dce/Chart.yaml
- charts/sonarqube/CHANGELOG.md
- charts/sonarqube/Chart.lock
- charts/sonarqube/Chart.yaml
- tests/unit-compatibility-test/fixtures/sonarqube-dce/ingress-with-controller.yaml
- tests/unit-compatibility-test/fixtures/sonarqube/ingress-with-controller.yaml
[SONAR-24702](https://sonarsource.atlassian.net/browse/SONAR-24702)
[SONAR-24702]: https://sonarsource.atlassian.net/browse/SONAR-24702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24702 Update ingress-nginx to 4.12.1

- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
- .github/workflows/next-scan.yml
- .github/workflows/release.yml
- .github/workflows/slack_notify.yml
[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BUILD-8073 Migrate public repositories workflows to large runners

- .cirrus/tasks.yml
[SONAR-25113](https://sonarsource.atlassian.net/browse/SONAR-25113)
[SONAR-25113]: https://sonarsource.atlassian.net/browse/SONAR-25113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25113 increase fixture memory to prevent oom killed
