SonarSource/helm-chart-sonarqube

charts/sonarqube/values.yaml
=> minor typo fix

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/secret.yaml
=> fixe invalid yaml rendering in secret.yaml

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
This PR aims to fix 2 of the reported Issues with the this chart.
It also artificially limits the full sonarqube deployment name to 33 characters as a proposed fix for #30, however this can also be solved differently and I am open for feedback.
* add missing imagePullSecrets to sts
* fix too long names globally (on a `_helpers.tpl` level)
* fixes #31
=> fix: minor issues

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
Adds support for the hostAlias parameter to the deploymentType statefulset.
fixes #40
=> Support hostAliases for deploymentType statefulsets

.github/workflows/lint-test.yml
QA is currently failing because the control plane does not get ready. hopefully the update will fix this
=> updated kind action version

.cirrus/upload_chart.sh
The build name is the same as the repo name
=> Fix build name

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
=> fixed use of sonarSecretProperties. 

charts/sonarqube-dce/values.yaml
* increase initial delay
* increase failure threshold for startup probe
=> Adjust probes

charts/sonarqube/README.md
https://jira.sonarsource.com/browse/SONAR-15251
Relates to https://github.com/SonarSource/sonar-enterprise/pull/4528
=> SONAR-15251 Add upgrade instructions

charts/sonarqube-dce/templates/sonarqube-application.yaml
Search nodes were already configured
=> SONAR-11094 add node name to app node

charts/sonarqube-lts/Chart.yaml, charts/sonarqube/Chart.yaml
Include security scanning, because that's what we do !
=> Update description of SonarQube

charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml
Some remarks after the release is published on artifact hub.
=> Minor Fixes

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/_helpers.tpl, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/_helpers.tpl, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
=> DOCKER-14 and DOCKER-13

charts/sonarqube-lts/CHANGELOG.md, charts/sonarqube-lts/Chart.yaml, charts/sonarqube-lts/values.yaml
=> Fixed default app version for LTS chart

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/_helpers.tpl, charts/sonarqube-dce/templates/secret.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
DOCKER-29 Support ES auth in helm chart
DOCKER-17 Link to community forum as support channel
DOCKER-33 Switch liveness probe to the correct endpoint
=> DOCKER-17, DOCKER-29 and DOCKER-33

charts/sonarqube-dce/README.md
+-1 mistake -.- 
CI run and version bump not needed as this is just a readme change
=> [SKIP CI] fixed wrong pkcs version information

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
Use the port's name as its value is configurable.
=> Use port's name

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/requirements.lock, charts/sonarqube-dce/requirements.yaml, charts/sonarqube-dce/templates/change-admin-password-hook.yml, charts/sonarqube-dce/templates/ingress.yaml, charts/sonarqube-dce/templates/networkpolicy.yaml, charts/sonarqube-dce/templates/podDistributionBudget.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/requirements.lock, charts/sonarqube/requirements.yaml, charts/sonarqube/templates/change-admin-password-hook.yml, charts/sonarqube/templates/ingress.yaml, charts/sonarqube/templates/networkpolicy.yaml, charts/sonarqube/values.yaml
We should probably bump the version number of the DCE chart to 1.0.0 when we release SQ 9.3
=> MMF-2019 Harden Helm Charts before graduating DCE chart from beta

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.yaml
=> DOCKER-39 detach edition from version

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
Probes were not working correctly
=> Revert #142

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/_helpers.tpl, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/_helpers.tpl, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.yaml
=> DOCKER-45 added caCerts.enabled implementation

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
=> DOCKER-47 added missing livenessProbe.failureThreshold

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
=> DOCKER-49 only one (Properties or SecretProperties) is needed

charts/sonarqube-dce/README.md, charts/sonarqube/README.md
fix a display problem in the NetworkPolicies README sections of the sonarqube and sonarqube-dce charts
=> [skip ci] Fix sonarqube and sonarqube-dce READMEs

.github/workflows/release.yml
=> BUILD-1663 Update to release action v4

charts/sonarqube-lts/OWNERS
=> Remove Tobias from owners :sadpanda:

.github/actions/helm-index/Dockerfile, .github/actions/helm-index/action.yml, .github/actions/helm-index/entrypoint.sh, .github/workflows/release.yml
**This was successfully tested on this fork: https://github.com/drautureau-sonarsource/helm-chart-sonarqube**
=> BUILD-1675 Remove helm-index GitHub action from gh-action_release

index.html
=> Add link to project

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/requirements.yaml, charts/sonarqube-dce/templates/change-admin-password-hook.yml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/requirements.yaml, charts/sonarqube/templates/change-admin-password-hook.yml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.schema.json, charts/sonarqube/values.yaml
=> Release/lge/restore changes after release 9.6.1

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/tests/sonarqube-test.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/tests/sonarqube-test.yaml, charts/sonarqube/values.yaml
- Add Values parameter tests.image
- Update Outdated README
=> DOCKER-73 allow test image to be configurable in helm chart

examples/grafana/sonarqube-dashboard.json, examples/grafana/sonarqube-dce-dashboard.json, examples/grafana/sonarqube-loki-dashboard.json
- Fixing typo for metric name  in Grafana Dashboard json files - sonarqube_health_web_status
=> Fix typo for sonarqube_health_web_status

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/config.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/config.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
- fix condition in helm templating for sonar.properties ConfigMap
- fix condition in helm templating for volumeMounts of this sonar.properties data
tests:
- templating locally with various .values file
- ct tests
- golden test on [that branch](https://github.com/SonarSource/helm-chart-sonarqube/tree/staging/jco/terratest-helm-chart)
- integration test by hand with various .values files
=> DOCKER-71 fix wrong condition for sonarSecretKey in helm-chart

.cirrus.yaml, charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/values.yaml
=> REL-2450 Release SonarQube 9.7.1

.cirrus.star, .cirrus.yaml, .cirrus/Dockerfile
=> BUILD-2271 Migrate to CirrusCI on AWS

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml
replace logo with static github resource
=> SQHELM-114 bump master version to differenciate from lts lifecycle

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/templates/sonarqube-search.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.yaml
* Adds timeoutSeconds parameter to probes
* Fixes typo in comment
---------
Co-authored-by: Sebastián Greco <38133294+pupseba@users.noreply.github.com>
This PR is based on the contribution made by Sebastián Greco in the context of [this PR](https://github.com/SonarSource/helm-chart-sonarqube/pull/280).
=> SQHELM-106 add timeoutSeconds to probe

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/install-plugins.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/install-plugins.yaml
Co-authored-by: @thomasgl-orange 
This PR is based on the contribution made by 
Thomas de Grenier de Latour in the context of https://github.com/SonarSource/helm-chart-sonarqube/pull/307.
=> SQHELM-116 install_plugins.sh: fix plugins deletion

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml
Prepare master for receiving 10.1.0 release cycle
=> NO-JIRA prepare 10.1.0 release cycle

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/change-admin-password-hook.yml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/change-admin-password-hook.yml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.yaml, tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml, tests/dynamic-compatibility-test/sonarqube/all-values.yaml, tests/unit-compatibility-test/sonarqube-dce/change-admin-password-hook-values.yaml, tests/unit-compatibility-test/sonarqube-dce/secret-values.yaml, tests/unit-compatibility-test/sonarqube/change-admin-password-hook-values.yaml, tests/unit-compatibility-test/sonarqube/secret-values.yaml
Updates the cURL image we are using from 7.76.1 to 8.2.0
=> SONAR-19950 Updates cURL image to 8.2.0

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/templates/_helpers.tpl, charts/sonarqube-dce/templates/change-admin-password-hook.yml, charts/sonarqube-dce/templates/ingress.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/values.schema.json, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/templates/_helpers.tpl, charts/sonarqube/templates/change-admin-password-hook.yml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/ingress.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.schema.json, charts/sonarqube/values.yaml, tests/unit-compatibility-test/sonarqube-dce/sonar-web-context-deprecated-values.yaml, tests/unit-compatibility-test/sonarqube-dce/sonar-web-context-values.yaml, tests/unit-compatibility-test/sonarqube/sonar-web-context-deprecated-values.yaml, tests/unit-compatibility-test/sonarqube/sonar-web-context-values.yaml
This reverts commit e41eaa71602519f592ce9db8ce05df420530bcc5 and fix the reason of the revert
=> SONAR-18991 simplify sonar web context

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md
=> SONAR-20151 Fixes Monitoring table

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/change-admin-password-hook.yml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/change-admin-password-hook.yml
=> SONAR-20474 Enable post-upgrade in the change-admin-password hook

.cirrus.yaml, .cirrus/docker_hub_test_pull_secret.yaml, charts/sonarqube-dce/ci/cirrus-values.yaml, charts/sonarqube/ci/cirrus-values.yaml
fix docker rate limit by adding pullsecret login
NO-JIRA fix typo in cirrus yaml
=> SONAR-20543 fix docker rate limit by adding pullsecret login

.cirrus.yaml, .cirrus/wait_for_kind.sh
Add a retry mechanism at creation time, this should prevent flakyness
=> SONAR-20657 change wait for kind behavior

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/sonarqube-application.yaml, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml, charts/sonarqube/values.yaml
Use default [cleanup policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy) but add the possibility to override it for Deployments
=> Add revisionHistoryLimit configuration

.cirrus/Dockerfile, charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/values.yaml
=> REL-2988 Release charts for SonarQube 9.9.4

.cirrus/Dockerfile, charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube-dce/values.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/values.yaml
=> REL-3003 Release SonarQube 10.4.1

charts/sonarqube-dce/README.md, charts/sonarqube/README.md
=> SONAR-21908 Change wording according to the concept of active version

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/deployment.yaml, charts/sonarqube/templates/sonarqube-sts.yaml
Continuation of https://github.com/SonarSource/helm-chart-sonarqube/pull/404, fixing dualstack/ipv6 probes for SonarQube CE variant only
=> fix: Enable dualstack/v6 in probes

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/_pod.tpl
=> Fix typo in the STS template

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[SONAR-23867](https://sonarsource.atlassian.net/browse/SONAR-23867)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last line! …
=> SONAR-23867 Add Jira integration

charts/sonarqube/README.md
[SONAR-24109](https://sonarsource.atlassian.net/browse/SONAR-24109)
Some minor fixes to readme
[SONAR-24109]: https://sonarsource.atlassian.net/browse/SONAR-24109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24109 Update README.md

google-cloud-marketplace-k8s-app/data-test/schema.yaml, google-cloud-marketplace-k8s-app/schema.yaml
[SONAR-24133](https://sonarsource.atlassian.net/browse/SONAR-24133)
[SONAR-24133]: https://sonarsource.atlassian.net/browse/SONAR-24133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24133 Add monitoringPasscode as a required parameter in GCP installations

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md
[SONAR-24128](https://sonarsource.atlassian.net/browse/SONAR-24128)
[SONAR-24128]: https://sonarsource.atlassian.net/browse/SONAR-24128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24128 Support Openshift v4.17

.cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml, .cirrus/upload_chart.sh
[SGB-270](https://sonarsource.atlassian.net/browse/SGB-270)
[SGB-270]: https://sonarsource.atlassian.net/browse/SGB-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SGB-270 Fixes upload_chart script

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/ci/cirrus-values.yaml, charts/sonarqube/openshift-verifier/values.yaml, charts/sonarqube/values.yaml, tests/unit-test/schema_test.go, tests/unit-test/test-cases-values/sonarqube/test-build-number.yaml
[REL-3507](https://sonarsource.atlassian.net/browse/REL-3507)
[REL-3507]: https://sonarsource.atlassian.net/browse/REL-3507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the community-build number included in the release

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.lock, charts/sonarqube-dce/Chart.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.lock, charts/sonarqube/Chart.yaml, tests/unit-compatibility-test/fixtures/sonarqube-dce/ingress-with-controller.yaml, tests/unit-compatibility-test/fixtures/sonarqube/ingress-with-controller.yaml
[SONAR-24224](https://sonarsource.atlassian.net/browse/SONAR-24224)
[SONAR-24224]: https://sonarsource.atlassian.net/browse/SONAR-24224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24224 Update the nginx-ingress to 4.12.0

.cirrus/tasks_gcp_marketplace.yml
[SONAR-24631](https://sonarsource.atlassian.net/browse/SONAR-24631)
[SONAR-24631]: https://sonarsource.atlassian.net/browse/SONAR-24631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24631 Fixes GCP release tasks

.cirrus/tasks.yml, .cirrus/tasks_env.yml, .cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml
[SONAR-24760](https://sonarsource.atlassian.net/browse/SONAR-24760)
[SONAR-24760]: https://sonarsource.atlassian.net/browse/SONAR-24760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24760 Enable the full QA during our nightly job

.cirrus/tasks.yml, .cirrus/tasks_env.yml, .cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml
[SONAR-24760](https://sonarsource.atlassian.net/browse/SONAR-24760)
[SONAR-24760]: https://sonarsource.atlassian.net/browse/SONAR-24760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24760 Enable the full QA during our nightly job on LTA

.cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, ct-sonarqube-dce-test.yaml, ct-sonarqube-test.yaml
[SONAR-24708](https://sonarsource.atlassian.net/browse/SONAR-24708)
[SONAR-24708]: https://sonarsource.atlassian.net/browse/SONAR-24708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24708 fix test always running both chart

.cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml
[SONAR-24854](https://sonarsource.atlassian.net/browse/SONAR-24854)
[SONAR-24854]: https://sonarsource.atlassian.net/browse/SONAR-24854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24854 Disable automated testing on Openshift due to upgrade

README.md
[SONAR-25095](https://sonarsource.atlassian.net/browse/SONAR-25095)
Part of 
[SONAR-25095]: https://sonarsource.atlassian.net/browse/SONAR-25095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25095 update contributing process

charts/sonarqube-dce/README.md
[SONAR-25112](https://sonarsource.atlassian.net/browse/SONAR-25112)
[SONAR-25112]: https://sonarsource.atlassian.net/browse/SONAR-25112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25112 fix minor radme typo for 9.9

charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/templates/change-admin-password-hook.yaml, charts/sonarqube-dce/templates/secret.yaml, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/templates/change-admin-password-hook.yaml, charts/sonarqube/templates/secret.yaml, tests/unit-compatibility-test/fixtures/sonarqube-dce/change-admin-password-hook-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube-dce/secret-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube-dce/sonar-web-context-deprecated-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube-dce/sonar-web-context-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/change-admin-password-hook-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/non-default-security-context-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/secret-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/sonar-web-context-deployment-deprecated-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/sonar-web-context-sts-deprecated-values.yaml, tests/unit-compatibility-test/fixtures/sonarqube/sonar-web-context-values.yaml
[SONAR-25075](https://sonarsource.atlassian.net/browse/SONAR-25075)
Part of 
[SONAR-25075]: https://sonarsource.atlassian.net/browse/SONAR-25075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25075 fix change admin password hook with special characters

charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, charts/sonarqube/ci/cirrus-values.yaml, charts/sonarqube/openshift-verifier/values.yaml, charts/sonarqube/values.yaml, tests/unit-test/schema_test.go, tests/unit-test/test-cases-values/sonarqube/test-build-number.yaml
[SONAR-24582](https://sonarsource.atlassian.net/browse/SONAR-24582)
[SONAR-24582]: https://sonarsource.atlassian.net/browse/SONAR-24582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-24582 Helm chart support policy for the latest SQCB

.cirrus/tasks_release.yml, .cirrus/tasks_templates.yml
[SONAR-25113](https://sonarsource.atlassian.net/browse/SONAR-25113)
[SONAR-25113]: https://sonarsource.atlassian.net/browse/SONAR-25113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25113 preventive increase of CI memory to prevent OOMKill

google-cloud-marketplace-k8s-app/Dockerfile
[SONAR-25234](https://sonarsource.atlassian.net/browse/SONAR-25234)
[SONAR-25234]: https://sonarsource.atlassian.net/browse/SONAR-25234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25234 update gcp helm deployer base

google-cloud-marketplace-k8s-app/Dockerfile
[SONAR-25234](https://sonarsource.atlassian.net/browse/SONAR-25234)
[SONAR-25234]: https://sonarsource.atlassian.net/browse/SONAR-25234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25234 update gcp help deployer base

charts/sonarqube-dce/README.md, charts/sonarqube/README.md
[DOC-2073](https://sonarsource.atlassian.net/browse/DOC-2073)
Part of 
[DOC-2073]: https://sonarsource.atlassian.net/browse/DOC-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOC-2073 update URLs to the Sonar docs

.cirrus/Dockerfile, .cirrus/generate_helm_fixtures.sh, .cirrus/setup.sh, .cirrus/setup_kind_vm.sh, .cirrus/tasks.yml, .cirrus/tasks_env.yml, .cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml, .cirrus/unit_helm_compatibility_test.sh, charts/sonarqube-dce/CHANGELOG.md, charts/sonarqube-dce/Chart.lock, charts/sonarqube-dce/Chart.yaml, charts/sonarqube-dce/README.md, charts/sonarqube/CHANGELOG.md, charts/sonarqube/Chart.lock, charts/sonarqube/Chart.yaml, charts/sonarqube/README.md, renovate.json, tests/unit-compatibility-test/fixtures/sonarqube-dce/ingress-with-controller.yaml, tests/unit-compatibility-test/fixtures/sonarqube/ingress-with-controller.yaml
[SONAR-25242](https://sonarsource.atlassian.net/browse/SONAR-25242)
[SONAR-25242]: https://sonarsource.atlassian.net/browse/SONAR-25242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25242 implement renovate for helm ci

.cirrus/tasks.yml, .cirrus/tasks_sonarqube.yml, .cirrus/tasks_sonarqube_dce.yml, .cirrus/tasks_templates.yml, charts/sonarqube/CHANGELOG.md
[SONAR-25528](https://sonarsource.atlassian.net/browse/SONAR-25528)
[SONAR-25528]: https://sonarsource.atlassian.net/browse/SONAR-25528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25528 Skip conditions to trigger package tasks in the event of releases

.github/workflows/release.yml
[SONAR-25631](https://sonarsource.atlassian.net/browse/SONAR-25631)
[SONAR-25631]: https://sonarsource.atlassian.net/browse/SONAR-25631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25631 Fix security hotspot githubactions:S7637

.cirrus/azure_app_verify_and_publish.sh, .cirrus/tasks_azure_marketplace.yml, azure-marketplace-k8s-app/createUIDefinition.json, azure-marketplace-k8s-app/mainTemplate.json, azure-marketplace-k8s-app/manifest.yaml, azure-marketplace-k8s-app/sonarqube-azure/Chart.yaml, azure-marketplace-k8s-app/sonarqube-azure/values.yaml
[SONAR-25731](https://sonarsource.atlassian.net/browse/SONAR-25731)
[SONAR-25731]: https://sonarsource.atlassian.net/browse/SONAR-25731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SONAR-25731 fix jdbc overwrite enabled set to string
